\documentclass{article}
\usepackage{longtable}
\usepackage{multirow}
\usepackage{dcolumn}


\begin{document}
\SweaveOpts{concordance=TRUE}

\section*{Test}
<<results=tex>>=



#library("compareGroups")
#data("regicor", package = "compareGroups")

source("C:/Users/adupont/Documents/projetstlouis/scripts/init.R")
source("C:/Users/adupont/Documents/projetstlouis/scripts/import.R")
source("C:/Users/adupont/Documents/projetstlouis/scripts/survie.R")

print(xtable (w ,
caption= "",
label="tab:connaissance2",
table.placement="htp",caption.placement="top"),
tabular.environment="longtable",
floating=F,
include.rownames=F,
sanitize.text.function = function(x){x}  )


print(xtable (WD ,
caption= "",
label="tab:connaissance2",
table.placement="htp",caption.placement="top"),
tabular.environment="longtable",
floating=F,
include.rownames=F,
sanitize.text.function = function(x){x}  )






res <- compareGroups(anapathc ~ ., data = greffe[,c("anapathc","disease_status_at_transplantc","sex_dp")])

 
restab <- createTable(res, hide.no = "no", type = 2,show.all = TRUE,show.n = T)

export2latex(restab, loc = "bottom",caption = "Descriptives by year.", size = "small")



stargazer(z, title="Regression Results",align=TRUE, no.space=TRUE,apply.coef = exp,omit.stat = c("ll"),ci=T)




@





\end{document}